# Generated by Django 4.1 on 2022-09-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0002_alter_produto_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
