# Generated by Django 4.1 on 2022-09-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentarios',
            new_name='comentario',
        ),
    ]
