# Generated by Django 4.1 on 2022-10-01 16:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("principal", "0002_rename_listadetarefas_terefa"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Terefa",
            new_name="Tarefa",
        ),
    ]
