# Generated by Django 4.1 on 2022-10-12 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("principal", "0002_tarefa_codigo_alter_tarefa_previsao_conclusao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
