# Generated by Django 4.1 on 2022-10-03 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("principal", "0003_rename_terefa_tarefa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarefa",
            name="usuario",
        ),
    ]
